### PR TITLE
feat(common): add API service

### PR DESCRIPTION
**Pull request by Clement-Z4RM**

### CODE REVIEW

**Review by Ximaz — APPROVED** [review]
I'm wonrdering about i18n if it wouldn't be easier to use HTTP status code as key for the error messages, so that you can pass the HTTP status of an API response to get the error. You wouldn't need to map the error to some keys.

**Comment by Clement-Z4RM** [comment]
> I'm wondering about i18n if it wouldn't be easier to use HTTP status code as key for the error messages, so that you can pass the HTTP status of an API response to get the error. You wouldn't need to map the error to some keys.

On the swagger, has an HTTP error always the same description?

**Review by capuchegianni — APPROVED** [review]

**Comment by Ximaz** [comment]
> > I'm wondering about i18n if it wouldn't be easier to use HTTP status code as key for the error messages, so that you can pass the HTTP status of an API response to get the error. You wouldn't need to map the error to some keys.
> 
> 
> 
> On the swagger, has an HTTP error always the same description?

Technically, yeah. 404 means "not found" whatever the route.

**Comment by Clement-Z4RM** [comment]
Okay si I’ll remove it

**Comment by Clement-Z4RM** [comment]
@Ximaz I therefore removed the `errorKey` property from common/api responses, so we just use the `status`.

**Comment by Ximaz** [comment]
> @Ximaz I therefore removed the `errorKey` property from common/api responses, so we just use the `status`.

Faire enough, as long as you don't edit the .d.ts files that I push as they may change in the future and get overwrote.

**Review by Ximaz — APPROVED** [review]

**Pull request merged**
