### PR TITLE
fix(ci): backend docker build

### PR DESCRIPTION
**Pull request by Ximaz**

### CODE REVIEW

**Comment by Clement-Z4RM** [comment]
@Ximaz 

I think it should be better (and it's a good practice) to use this Dockerfile:
```Dockerfile
FROM alpine:3.20.3 AS base

LABEL org.opencontainers.image.source=https://github.com/zowks/B-DEV-500-area

RUN apk update                 \
    && apk upgrade             \
    && apk add npm=10.8.0-r0   \
    && rm -rf /var/cache/apk/*

FROM base AS setup

WORKDIR /tmp/app/

COPY .npmrc .npmrc

COPY package.json package.json

COPY package-lock.json package-lock.json

COPY apps/backend/package.json apps/backend/package.json

COPY apps/backend/tsconfig.build.json apps/backend/tsconfig.build.json

COPY apps/backend/tsconfig.json apps/backend/tsconfig.json

COPY apps/backend/src/ apps/backend/src/

COPY apps/backend/prisma/ apps/backend/prisma/

RUN npm install

FROM setup AS build

WORKDIR /tmp/app/apps/backend

RUN npm run prisma:generate

RUN npm run build

FROM build AS serve

COPY --from=build /tmp/app/.npmrc /app/.npmrc

COPY --from=build /tmp/app/package.json /app/package.json

COPY --from=build /tmp/app/package-lock.json /app/package-lock.json

COPY --from=build /tmp/app/apps/backend/ /app/apps/backend/

WORKDIR /app

RUN npm install --production

WORKDIR /app/apps/backend

ENTRYPOINT [ "npm", "run", "container" ]
```
It first installs the packages at the root using the `package-lock.json` and then copy only the `backend` - so if other worspace packages were installed, they aren't in the final container.

I tried on my side, it works well. The only thing I'm not sure about is the build in the CI, but I can't try it on my machine.

I just need your approval to commit this, I have all the changes needed ready to be pushed.

**Comment by Ximaz** [comment]
> @Ximaz 
> 
> 
> 
> I think it should be better (and it's a good practice) to use this Dockerfile:
> 
> ```Dockerfile
> 
> FROM alpine:3.20.3 AS base
> 
> 
> 
> LABEL org.opencontainers.image.source=https://github.com/zowks/B-DEV-500-area
> 
> 
> 
> RUN apk update                 \
> 
>     && apk upgrade             \
> 
>     && apk add npm=10.8.0-r0   \
> 
>     && rm -rf /var/cache/apk/*
> 
> 
> 
> FROM base AS setup
> 
> 
> 
> WORKDIR /tmp/app/
> 
> 
> 
> COPY .npmrc .npmrc
> 
> 
> 
> COPY package.json package.json
> 
> 
> 
> COPY package-lock.json package-lock.json
> 
> 
> 
> COPY apps/backend/package.json apps/backend/package.json
> 
> 
> 
> COPY apps/backend/tsconfig.build.json apps/backend/tsconfig.build.json
> 
> 
> 
> COPY apps/backend/tsconfig.json apps/backend/tsconfig.json
> 
> 
> 
> COPY apps/backend/src/ apps/backend/src/
> 
> 
> 
> COPY apps/backend/prisma/ apps/backend/prisma/
> 
> 
> 
> RUN npm install
> 
> 
> 
> FROM setup AS build
> 
> 
> 
> WORKDIR /tmp/app/apps/backend
> 
> 
> 
> RUN npm run prisma:generate
> 
> 
> 
> RUN npm run build
> 
> 
> 
> FROM build AS serve
> 
> 
> 
> COPY --from=build /tmp/app/.npmrc /app/.npmrc
> 
> 
> 
> COPY --from=build /tmp/app/package.json /app/package.json
> 
> 
> 
> COPY --from=build /tmp/app/package-lock.json /app/package-lock.json
> 
> 
> 
> COPY --from=build /tmp/app/apps/backend/ /app/apps/backend/
> 
> 
> 
> WORKDIR /app
> 
> 
> 
> RUN npm install --production
> 
> 
> 
> WORKDIR /app/apps/backend
> 
> 
> 
> ENTRYPOINT [ "npm", "run", "container" ]
> 
> ```
> 
> It first installs the packages at the root using the `package-lock.json` and then copy only the `backend` - so if other worspace packages were installed, they aren't in the final container.
> 
> 
> 
> I tried on my side, it works well. The only thing I'm not sure about is the build in the CI, but I can't try it on my machine.
> 
> 
> 
> I just need your approval to commit this, I have all the changes needed ready to be pushed.

I believe this won't work : 'apps/backend/*' when copying. The CI uses a 'working_directory' to apps/backend already. The path 'apps/backend/apps/backend' will not exist, will it ?

**Comment by Clement-Z4RM** [comment]
> I believe this won't work : 'apps/backend/*' when copying. The CI uses a 'working_directory' to apps/backend already. The path 'apps/backend/apps/backend' will not exist, will it ?

Yes you're right, but I changed this. Now, it'll be like in the Docker compose:
```yml
      - name: "Build the image"
        id: "push"
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./apps/backend/Dockerfile
          push: true
          tags: ghcr.io/zowks/area-backend:latest
```

**Comment by Ximaz** [comment]
You should poen a PR then.

**Pull request closed without merging**
