### PR TITLE
merge: `frontend/feature/area-creation` into `common/dev`

### PR DESCRIPTION
**Pull request by Clement-Z4RM**
- Add mobile Docker build
- Merge (and move) hash string/password function of mobile into common and use it in both frontend and mobile (4cb96f2 and da5d9d3)
- Move `isEmail` utility function from frontend to common so it can be used in mobile (bfa53a6)
- Add `serviceName` to get service name from its id ~~and `oauthServiceNames`~~ utility function~~s~~ (a5ce0d9, 2c1a3f7 and 0ddc8345)
- Add `Services` and other services-related types to common (9c20a9c, bb8e528 and f19e27c7)
- Changes on API:
  - Rename type `Service` to `OAuthService` (8063f95 and b748731)
  - Change/add response status codes for OAuth request to fit with the recent backend changes (b6d6ad9)
  - Add return body to OAuth callback request (containing the ID of the created OAuth credentials) (ec5e878)
  - Fix the return type for OAuth credentials request (3f284e5)
- There are other changes from backend, frontend and mobile due to merges

---

I'm working on a proper/good way to link an Action to a REAction with constants in `common`. Here's a preview of what I've done for the moment:
```ts
export const ACTIONS: Record<string, Field<keyof AreaYouTubeVideo>[]> = {
    "youtube.on_liked_video": [
        { name: "id", type: "text" },
        { name: "url", type: "text" },
        { name: "title", type: "text" },
        { name: "description", type: "text" },
        { name: "channelName", type: "text" },
        { name: "channelId", type: "text" },
        { name: "likes", type: "text" },
        { name: "views", type: "text" },
        { name: "publishedAt", type: "date" },
        { name: "tags", type: "text" },
        { name: "thumbnail", type: "text" }
    ]
};
```
> ~~Maybe it'll be in the backend, see the following discussion for more details.~~ Too restrictive, it'll simply be on `common`.

### CODE REVIEW

**Comment by Ximaz** [comment]
I strongly discourage you to hardcode fields for the AREAs as they are already in about.json route, and might, or some may be added, depending on the AREAs. At the end, you are the frontend team and be the one to use them, but I don't think this is a good idea for you.

**Comment by Ximaz** [comment]
What we might do instead is setting the types on the backend route, so that you fetch them at the same time, but I really don't think it's a good idea to store them on the client side.

**Comment by Clement-Z4RM** [comment]
> @Ximaz

I'm totally agree with you, but given that actually, there isn't any field in the `/about.json`, I started to write them manually in `common`.
But yeah, it would be even better to fetch them from the backend.
The only problem is the time: we have less than 48 hours left to work on the backend. So do we take time to do this, or let we them in `common`, so we can edit them until the defense?

**Comment by Ximaz** [comment]
> > @Ximaz
> 
> I'm totally agree with you, but given that actually, there isn't any field in the `/about.json`, I started to write them manually in `common`. But yeah, it would be even better to fetch them from the backend. The only problem is the time: we have less than 48 hours left to work on the backend. So do we take time to do this, or let we them in `common`, so we can edit them until the defense?

Go ahead bud, we keep doing that in frontend.

**Review by capuchegianni — APPROVED** [review]
Nothing to say, looks good to me

**Pull request merged**
