### PR TITLE
build(docker): rewrite backend Dockerfile so it should be built at the root

### PR DESCRIPTION
**Pull request by Clement-Z4RM**

### CODE REVIEW

**Comment by Ximaz** [comment]
Is that it ? I don't see your changes as my commit is my last one.

**Comment by Clement-Z4RM** [comment]
> Is that it ? I don't see your changes as my commit is my last one.

I'm not sure that I'm understanding what do you mean, but if you mean "what is the commit editing the Dockerfile", it's the 035d4ee3

**Comment by Ximaz** [comment]
> > Is that it ? I don't see your changes as my commit is my last one.
> 
> I'm not sure that I'm understanding what do you mean, but if you mean "what is the commit editing the Dockerfile", it's the [035d4ee](https://github.com/zowks/B-DEV-500-area/commit/035d4ee3e76321dd7956518907a6e15d17a8592f)

I'm talking about the backend CI where you had fix the `workflow-directory` to not mess up the Dockerfile build.

**Comment by Clement-Z4RM** [comment]
> I'm talking about the backend CI where you had fix the `workflow-directory` to not mess up the Dockerfile build.

Oh okay. It's in this commit: 488452d. The `context` was changed to the root, and a `file` property was added, containing the path of the backend Dockerfile from the root.
I temporarily activated the backend CI on this branch (f5e738f) and it works well: https://github.com/zowks/B-DEV-500-area/actions/runs/11315177690.

**Review by Ximaz — APPROVED** [review]

**Pull request merged**
